descriptions = [
    "forest scene", 
    "portrait of an unknown figure", 
    "bustling cityscape", 
    "tranquil ocean view", 
    "mountainous landscape",
    "desert at sunset",
    "candlelit dinner setting",
    "abandoned amusement park",
    "starry night sky",
    "underwater coral reef",
    "medieval castle",
    "futuristic metropolis",
    "flower-filled meadow",
    "rain-soaked street",
    "autumnal forest path",
    "snow-covered village",
    "sunrise over a valley",
    "ancient ruins",
    "mystical island",
    "cosmic nebula",


    "roaring 1920s city street",
    "serene Japanese garden",
    "hauntingly empty theater",
    "vibrant carnival parade",
    "lonely lighthouse on a cliff",
    "breathtaking alpine vista",
    "lush tropical jungle",
    "steampunk-inspired train station",
    "post-apocalyptic wasteland",
    "whimsical fairy-tale village",
    "intimate jazz club scene",
    "rooftop view at dusk",
    "enchanted forest clearing",
    "bustling spaceport",
    "ancient Egyptian tomb",
    "wild west ghost town",
    "Victorian-era ballroom dance",
    "pirate ship sailing the high seas",
    "majestic dragon's lair",
    "moonlit masquerade ball",
    "hidden underground cavern",
    "safari with wild animals",
    "medieval jousting tournament",
    "futuristic cyberpunk alleyway",
    "tranquil zen rock garden",
    "mystical floating islands",
    "grand emperor's palace",
    "secluded monastery in the mountains",
    "otherworldly alien landscape",
    "romantic Venetian canal",
     "sun-drenched vineyard",
    "bustling Moroccan market",
    "tranquil Tibetan monastery",
    "cosy cabin in a snowstorm",
    "underground city of moles",
    "celestial observatory under the stars",
    "vast alien desert with crystalline structures",
    "mystical library with floating books",
    "prehistoric valley with dinosaurs",
    "opulent Gatsby-era mansion party",
    "rainforest canopy with vibrant birds",
    "ancient Greek agora",
    "Nordic village under the aurora borealis",
    "underwater Atlantean city",
    "surreal dreamscape with floating islands",
    "Victorian London street in the fog",
    "grand Indian wedding procession",
    "sacred temple atop a misty mountain",
    "vibrant Rio de Janeiro carnival",
    "serene cherry blossom festival in Kyoto",
    "war-torn battlefield with medieval knights",
    "ethereal elven kingdom in an ancient forest",
    "sprawling African savannah with migrating herds",
    "intricate spider's web covered in morning dew",
    "grand coronation in a majestic cathedral",
    "cosmic event at the edge of a black hole",
    "lush oasis in the middle of a desert",
    "haunting abandoned asylum",
    "roaring campfire under a starry sky",
    "mystical druid circle in a dense forest",
    "futuristic city with flying cars",
    "ancient Mayan city in the jungle",
    "opulent ball in a French chateau",
    "wild rodeo in the American West",
    "breathtaking view from a mountain peak",
    "golden wheat field swaying in the breeze",
    "mysterious crop circles in rural farmland",
    "underground speakeasy during Prohibition",
    "vast Mongolian steppe with nomadic tribes",
    "sweeping view from a hot air balloon",
    "ancient Roman colosseum in its prime",
    "candlelit catacombs with hidden secrets",
    "breathtaking Northern Lights over an icy tundra",
    "lush Amazonian rainforest with hidden tribes",
    "grand pharaoh's procession in ancient Egypt",
    "whimsical chocolate factory with magical treats",
    "haunting shipwreck on a moonlit shore",
    "vibrant coral reef teeming with marine life",
    "majestic Arabian palace in an oasis",
    "bustling Silk Road caravan in the desert",
    "eerie swamp with will-o'-the-wisps",
    "opulent Renaissance fair in a European town",
    "cosmic dance of planets in an alien solar system",
    "intriguing detective scene in 1940s New York",
    "mystical Stonehenge during a solstice",
    "grand Russian ballroom during the Tsar era",
    "sweeping African plains at sunset with majestic wildlife",
    "intricate maze garden with hidden treasures",
    "futuristic Martian colony with biodomes",
    "idyllic Hobbit village in the Shire",
    "grand Central Asian yurt gathering",
    "mystical waterfall with hidden caves",
    "surreal Salvador Dali-esque dreamscape",
    "intimate geisha performance in old Kyoto",
    "vast Australian outback with unique wildlife",
    "intriguing archaeological dig uncovering ancient relics",
    "cosy Christmas market in a snowy European town",
    "vibrant Diwali celebration in Mumbai",
    "tranquil Zen garden with koi fish",
    "breathtaking cherry blossom avenue in full bloom",
    "haunting Gothic cathedral in moonlight",
    "whimsical winter wonderland with ice sculptures",
    "surreal floating city in the clouds",
    "mystical Arabian Nights scene with flying carpets",
    "grand medieval feast in a castle's great hall",
    "enchanting masquerade ball in Venice",
    "vast lavender fields in Provence",
    "surreal zero-gravity space station",
    "bustling bazaar in ancient Persia",
    "mystical fairy glen with shimmering lights",
    "grand Gothic castle on a stormy night",
    "vibrant Mardi Gras parade in New Orleans",
    "tranquil tea ceremony in a bamboo grove",
    "haunting ruins of a sunken city",
    "cosmic dance of galaxies colliding",
    "idyllic Grecian island with azure waters",
    "sweeping sand dunes in the Sahara at sunset",
    "majestic eagle's eye view of the Grand Canyon",
    "whimsical clockwork town with moving parts",
    "eerie Victorian mansion with hidden passages",
    "breathtaking bioluminescent bay at night",
    "grand opera performance in 19th-century Paris",
    "surreal landscape with floating mountains",
    "vibrant Day of the Dead celebration in Mexico",
    "mystical grove with ancient druid rituals",
    "bustling samurai market in Edo-period Tokyo",
    "haunting Celtic ruins under a full moon",
    "enchanting underwater ballroom dance",
    "sweeping views from a mountaintop monastery",
    "vibrant tulip fields in the Netherlands",
    "cosmic observatory in a distant galaxy",
    "idyllic French café scene on a rainy day",
    "majestic African safari with the Big Five",
    "whimsical winter village with gingerbread houses",
    "tranquil koi pond with blossoming lotuses",
    "surreal Salvador Dali-inspired desert landscape",
    "vibrant Holi festival in India with a burst of colors",
    "mystical aurora borealis over an icy glacier",
    "haunting abandoned theme park at dusk",
    "enchanting forest with bioluminescent fungi",
    "breathtaking view of Machu Picchu at sunrise",
    "surreal floating islands with cascading waterfalls",
    "vibrant jazz club in 1920s Harlem",
    "idyllic Mediterranean seaside village",
    "majestic view of the Milky Way from a desert oasis",
    "breathtaking sunrise over the Serengeti plains",
    "whimsical candy land with rivers of chocolate",
    "surreal floating temples in the sky",
    "vibrant streets of Rio during Carnival",
    "mystical ancient library with scrolls of knowledge",
    "haunting ghost town reclaimed by nature",
    "enchanting moonlit dance of fireflies in a meadow",
    "bustling streets of ancient Rome at its zenith",
    "idyllic hidden paradise behind a waterfall",
    "cosmic journey through a wormhole",
    "tranquil cherry blossom petals falling in slow motion",
    "majestic pyramids of Giza with a golden hue",
    "surreal landscape inside a crystal ball",
    "vibrant underwater city with merfolk",
    "hauntingly beautiful abandoned cathedral",
    "whimsical treehouses interconnected by bridges",
    "breathtaking view atop the Great Wall of China",
    "surreal world inside a painter's palette",
    "vibrant lantern festival on a serene lake",
    "mystical forest where trees have faces",
    "haunting ship sailing through the mists of time",
    "enchanting dance of the Northern Lights in Lapland",
    "bustling cyberpunk city with neon lights",
    "idyllic countryside during fall with leaves changing colors",
    "majestic view from the edge of a volcano",
    "surreal world where clouds are solid ground",
    "vibrant bustling souks of Marrakech",
    "mystical ancient tree glowing with runes",
    "haunting ruins of Atlantis",
    "whimsical carousel with mythical creatures",
    "breathtaking aerial view of Santorini's blue domes",
    "surreal desert with hourglass dunes",
    "vibrant festival of lights in an ancient temple",
    "mystical realm where dreams and reality blur",
    "haunting Victorian streets in a foggy London night",
    "enchanting realm where music takes physical form",
    "breathtaking fjords with auroras reflecting in the water",
    "surreal landscape of a world made of crystals",
    "vibrant bustling streets of a Renaissance fair",
    "majestic view of the universe from the edge of time",
    "enchanting midnight ball under the stars",
    "surreal landscape where oceans touch the sky",
    "vibrant bustling streets of Bangkok's night market",
    "mystical caverns illuminated by glow worms",
    "haunting abandoned castle overtaken by nature",
    "whimsical world inside a snow globe",
    "breathtaking view of cherry blossoms in Kyoto",
    "surreal cityscape where buildings float on clouds",
    "vibrant tapestry of life in a coral reef",
    "mystical realm where shadows come to life",
    "haunting echoes of a forgotten battlefield",
    "enchanting parade of lanterns in the night sky",
    "breathtaking panorama of the Himalayan peaks",
    "surreal gardens with plants made of glass",
    "vibrant and bustling streets of a Moroccan medina",
    "mystical frozen landscape under the auroras",
    "hauntingly serene ruins of a sunken city",
    "whimsical world where books fly like birds",
    "breathtaking dance of comets in the night sky",
    "surreal forest where leaves are made of gold",
    "vibrant festival in the heart of Rio de Janeiro",
    "mystical journey inside a pharaoh's tomb",
    "haunting melodies from an ancient amphitheater",
    "enchanting world where waterfalls flow upwards",
    "breathtaking view from a lighthouse at stormy sea",
    "surreal desert with oasis mirages",
    "vibrant colors of Holi festival in India",
    "mystical realm of floating islands and waterfalls",
    "haunting beauty of an ice cave",
    "whimsical journey on the back of a giant turtle",
    "breathtaking view of Earth from the moon's surface",
    "surreal city where roads spiral into the sky",
    "vibrant life in a hidden Amazonian village",
    "mystical dance of spirits in an enchanted forest",
    "hauntingly quiet winter night with falling snow",
    "enchanting realm of endless libraries",
    "breathtaking sunrise over a misty moor",
    "surreal landscape of a crystalline forest",
    "vibrant market day in medieval Europe",
    "majestic flight over an active volcano spewing lava",
    "enchanting dance of fireflies in a moonlit grove",
    "surreal world where time flows backward",
    "vibrant streets of Tokyo illuminated by neon lights",
    "mystical realm where constellations come alive",
    "haunting echoes of an ancient monastery",
    "whimsical journey through a candy-coated wonderland",
    "breathtaking view from the edge of Angel Falls",
    "surreal landscape where rivers flow in the sky",
    "vibrant tapestry of a bustling Indian railway station",
    "mystical twilight in a forest of bioluminescent trees",
    "haunting remnants of a post-apocalyptic city",
    "enchanting ballet of starfish in a tidal dance",
    "breathtaking aerial view of the Amazon rainforest",
    "surreal realm where dreams manifest as reality",
    "vibrant hues of a Caribbean carnival",
    "mystical pathways in a labyrinth of mirrors",
    "haunting beauty of a derelict Victorian mansion",
    "whimsical world where music paints the scenery",
    "breathtaking dance of the Northern Lights in Iceland",
    "surreal journey inside a kaleidoscope",
    "vibrant energy of a New York City jazz club in the 1920s",
    "mystical ruins of an ancient druidic henge",
    "haunting serenity of a fog-covered moor",
    "enchanting world where statues narrate stories",
    "breathtaking expanse of the Sahara under a starlit sky",
    "surreal floating gardens in a boundless ocean",
    "vibrant festivities of a Venetian masquerade ball",
    "mystical realm where each season lasts a day",
    "haunting whispers of a long-lost underwater civilization",
    "whimsical chase of autumn leaves in a playful wind",
    "breathtaking panorama of a city built on clouds",
    "surreal desert where sand dunes sing melodies",
    "vibrant life in a bustling African market",
    "mystical voyage aboard a ghost ship",
    "haunting beauty of a frozen waterfall",
    "enchanting night in a forest lit by glow-in-the-dark flowers",
    "breathtaking view from a mountaintop observatory",
    "surreal landscape where rainbows touch the ground",
    "vibrant energy of a flamenco dance in Seville",
    "majestic ruins of a castle floating on a lake"
]










