detailed_modifiers = [
    "anatomical precision", 
    "Fibonacci sequence patterns", 
    "vibrant color contrasts", 
    "intricate shadow play", 
    "geometric distortions",
    "kaleidoscopic patterns",
    "intricate lacework details",
    "bold chiaroscuro contrasts",
    "delicate pastel shades",
    "vibrant neon hues",
    "meticulous pointillism",
    "soft impressionistic strokes",
    "geometric fractal designs",
    "fluid organic shapes",
    "textured brushwork",
    "glossy reflective surfaces",
    "matte finishes",
    "holographic effects",
    "metallic gold and silver accents",
    "aged patina effects",
    "rough stone textures",
    "smooth marble-like finishes",
    "translucent glass-like effects",
    "gradient color transitions",
    "detailed cross-hatching",
    "bold block colors",
    "subtle watercolor washes",
    "vintage sepia tones",
    "saturated pop art colors",
    "monochromatic palettes",
    "duotone effects",
    "hand-drawn sketches",
    "photorealistic details",
    "abstract expressionist splatters",
    "cubist geometric shapes",
    "fauvist wild brushwork",
    "surrealist dreamlike elements",
    "baroque ornamental details",
    "rococo elegance and lightness",
    "gothic dark and moody tones",
    "renaissance classical proportions",
    "minimalist simplicity",
    "maximalist abundance",
    "futuristic cyber elements",
    "retro vintage motifs",
    "psychedelic swirling patterns",
    "art deco streamlined designs",
    "art nouveau organic motifs",
    "neoclassical grandeur",
    "romantic soft and dreamy effects",
    "realist everyday scenes",
    "mystical ethereal atmospheres",
    "steampunk mechanical details",
    "fantasy mythical elements",
    "horror eerie and macabre tones",
    "opulent jewel tones",
    "weathered rustic finishes",
    "collage-inspired layering",
    "whimsical fairy-tale motifs",
    "gritty urban textures",
    "celestial starry patterns",
    "fluid marbling effects",
    "tactile relief elements",
    "woven fabric-like textures",
    "mirrored reflective facets",
    "brushless finger painting effects",
    "dripping paint techniques",
    "burnished metallic sheens",
    "crystalline structures",
    "charcoal smudged effects",
    "stippled dot techniques",
    "scratchboard etching",
    "windswept dynamic lines",
    "mosaic-inspired detailing",
    "stained glass translucency",
    "wood grain textures",
    "oxidized metal effects",
    "tattoo-inspired designs",
    "calligraphic flourishes",
    "graffiti-inspired splashes",
    "ancient fresco techniques",
    "pop culture references",
    "folk art motifs",
    "tribal patterns and symbols",
    "digital pixel art elements",
    "3D sculptural reliefs",
    "negative space designs",
    "thermal color shifts",
    "UV reactive elements",
    "luminous glow-in-the-dark effects",
    "origami-inspired folds",
    "kinetic moving parts",
    "interactive touch-sensitive elements",
    "haptic textured feedback",
    "augmented reality overlays",
    "bioluminescent organisms",
    "hand-stitched embroidery",
    "beaded and sequined details",
    "pressed natural elements",
    "ceramic and porcelain finishes",
    "leather and suede textures",
    "feathered and furred details",
    "gemstone and crystal inlays",
    "wax seal imprints",
    "parchment and scroll elements",
    "intricate lace and tatting",
    "fluid ink washes",
    "bold graffiti tags",
    "ancient hieroglyphic symbols",
    "Victorian brocade patterns",
    "shimmering iridescent effects",
    "hand-carved woodblock prints",
    "detailed botanical illustrations",
    "distressed and aged patinas",
    "silk-screened patterns",
    "photographic negative effects",
    "layered papercut silhouettes",
    "bold typographic elements",
    "intricate mandala designs",
    "hand-spun pottery textures",
    "vibrant batik fabric patterns",
    "etched glass designs",
    "woven tapestry motifs",
    "metal embossed patterns",
    "intricate Celtic knots",
    "hand-painted ceramic tiles",
    "traditional quilt patterns",
    "intricate paisley designs",
    "bold tribal war paint",
    "delicate butterfly wing patterns",
    "vintage postcard motifs",
    "retro diner aesthetics",
    "shabby chic distressed finishes",
    "nautical rope and knot designs",
    "detailed anatomical sketches",
    "whimsical doodle art",
    "bold pop art comic styles",
    "intricate zentangle designs",
    "detailed architectural blueprints",
    "fluid acrylic pouring techniques",
    "vintage newspaper collage",
    "detailed topographical map designs",
    "bold superhero comic motifs",
    "intricate mehndi henna designs",
    "traditional Japanese ukiyo-e prints",
    "vibrant tropical flora and fauna",
    "detailed astronomical charts",
    "bold neon signage",
    "intricate spiderweb designs",
    "vintage lace doily patterns",
    "detailed bird feather motifs",
    "fluid Rorschach inkblot patterns",
    "vintage vinyl record motifs",
    "intricate snowflake designs",
    "bold geometric op art patterns",
    "soft pastel chalk gradients",
    "bold cubist fragmentation",
    "intricate filigree metalwork",
    "vibrant tie-dye swirls",
    "detailed scrimshaw carvings",
    "fluid sumi-e brush strokes",
    "vintage daguerreotype effects",
    "intricate macramé knotting",
    "bold chiaroscuro lighting",
    "detailed petroglyph carvings",
    "vibrant pointillist dots",
    "soft airbrushed gradients",
    "intricate tessellation patterns",
    "bold art brut rawness",
    "detailed cartographic elements",
    "fluid suminagashi marbling",
    "vintage cyanotype blueprints",
    "intricate beadwork patterns",
    "bold hard-edge color fields",
    "detailed scrimshaw etchings",
    "fluid ebru marbling swirls",
    "vintage ambrotype effects",
    "intricate chainmail weaving",
    "bold tenebrism contrasts",
    "detailed intaglio prints",
    "fluid gyotaku fish rubbings",
    "vintage ferrotype tones",
    "intricate broderie anglaise",
    "bold trompe-l'œil illusions",
    "detailed lithographic prints",
    "fluid wet-on-wet watercolors",
    "vintage wood veneer marquetry",
    "intricate guilloché patterns",
    "bold kinetic art movements",
    "detailed chiaroscuro reliefs",
    "fluid sgraffito scratchings",
    "vintage daguerreotype silhouettes",
    "intricate cloisonné enamelwork",
    "bold action painting splatters",
    "detailed bas-relief sculptures",
    "fluid brush calligraphy strokes",
    "vintage pinstripe designs",
    "intricate mosaic tesserae",
    "bold color field expanses",
    "vibrant aurora borealis hues",
    "intricate wrought ironwork designs",
    "soft-focus bokeh effects",
    "bold art nouveau swirls",
    "detailed terrazzo patterns",
    "fluid inkblot Rorschach patterns",
    "vintage hand-lettered calligraphy",
    "intricate arabesque motifs",
    "bold psychedelic kaleidoscope patterns",
    "detailed botanical pressed flowers",
    "fluid resin art swirls",
    "vintage sepia-toned photographs",
    "intricate tape lace designs",
    "bold street art murals",
    "detailed astronomical constellations",
    "fluid sand art patterns",
    "vintage daguerreotype portraits",
    "intricate parquetry designs",
    "bold graffiti tags and murals",
    "detailed anatomical illustrations",
    "fluid smoke and ink patterns",
    "vintage hand-tinted photographs",
    "intricate gemstone faceting",
    "bold abstract expressionist brushwork",
    "detailed architectural drafts",
    "fluid water ripple patterns",
    "vintage silhouette portraits",
    "intricate origami paper folds",
    "bold minimalist line art",
    "detailed cross-stitch patterns",
    "fluid lava lamp blobs",
    "vintage hand-painted ceramics",
    "intricate crochet patterns",
    "bold op art optical illusions",
    "detailed topiary designs",
    "fluid acrylic swipe techniques",
    "vintage hand-carved scrimshaw",
    "intricate stained glass patterns",
    "bold constructivist designs",
    "detailed mandala coloring",
    "fluid ink wash landscapes",
    "vintage hand-woven tapestries",
    "intricate quilling paper designs",
    "bold dadaist collages",
    "vibrant stained wood patterns",
    "intricate shadow puppetry designs",
    "soft-focus pastel smudges",
    "bold brutalist concrete textures",
    "detailed marionette carvings",
    "fluid glassblowing shapes",
    "vintage hand-stitched leatherwork",
    "intricate batik wax-resist patterns",
    "bold art deco streamlined motifs",
    "detailed scrimshaw on bone",
    "fluid molten metal pours",
    "vintage hand-forged metalwork",
    "intricate hand-tufted textiles",
    "bold cubist fragmented forms",
    "detailed hand-thrown pottery",
    "fluid raku pottery glazes",
    "vintage hand-bound book designs",
    "intricate hand-cut paper silhouettes",
    "bold surrealist dreamlike imagery",
    "detailed hand-spun yarn textures",
    "fluid poured acrylic cells",
    "vintage hand-set typography prints",
    "intricate hand-beaded jewelry designs",
    "bold fauvist wild brush strokes",
    "detailed hand-crafted mosaic tiles",
    "fluid wax encaustic brushwork",
    "vintage hand-etched glasswork",
    "intricate hand-woven basketry",
    "bold futurist dynamic forms",
    "detailed hand-dyed fabric patterns",
    "fluid kinetic sculpture movements",
    "vintage hand-made lace designs",
    "intricate hand-painted porcelain",
    "bold pop art comic strip motifs",
    "detailed hand-carved wood inlays",
    "fluid spin art centrifugal patterns",
    "vintage hand-crafted marionettes",
    "intricate hand-made paper mâché forms",
    

]




