
# Styles/Artists
styles_artists = [
    "Paul Klee", 
    "Salvador Dali", 
    "Picasso", 
    "Douglas Adams", 
    "Wes Anderson",
    "Vincent van Gogh",
    "Art Nouveau",
    "Cubism",
    "Frida Kahlo",
    "Impressionism",
    "Banksy's street art",
    "Baroque",
    "Hieronymus Bosch",
    "Pop Art",
    "Georgia O'Keeffe",
    "Abstract Expressionism",
    "Andy Warhol",
    "Renaissance",
    "H.R. Giger's biomechanical",
    "Surrealism",
    "Michelangelo",
    "Gothic Revival",
    "Katsushika Hokusai",
    "Art Deco",
    "Jackson Pollock's drip painting",
    "Romanticism",
    "Leonardo da Vinci",
    "Steampunk",
    "Yayoi Kusama's infinity nets",
    "Neoclassicism",
    "M.C. Escher's optical illusions",
    "Fauvism",
    "Rembrandt",
    "Cyberpunk aesthetics",
    "Claude Monet's Water Lilies",
    "Constructivism",
    "Edvard Munch",
    "Dadaism",
    "J.M.W. Turner's atmospheric seascapes",
    "Futurism",
    "Diego Rivera's murals",
    "Art Brut",
    "Gustav Klimt's golden phase",
    "Expressionism",
    "Joan Miró's abstract compositions",
    "Caravaggio's chiaroscuro",
    "Ukiyo-e woodblock prints",
    "Byzantine mosaic",
    "Marc Chagall's dreamlike imagery",
    "Op Art",
    "Amedeo Modigliani's elongated forms",
    "Tapestry of the Bayeux",
    "Roy Lichtenstein's comic book style",
    "Pre-Raphaelite Brotherhood",
    "Salvador Dali's melting clocks",
    "Art and Crafts Movement",
    "Egon Schiele's raw lines",
    "Minimalism",
    "Henri Rousseau's jungle scenes",
    "Post-Impressionism",
    "Kandinsky's abstract geometries",
    "Tiffany stained glass",
    "Keith Haring's bold lines",
    "Rococo's ornate elegance",
    "Bauhaus",
    "Grant Wood's American Gothic",
    "De Stijl",
    "Mary Cassatt's mother and child scenes",
    "Brutalism architecture",
    "Winslow Homer's seascapes",
    "Metaphysical art",
    "Alphonse Mucha's posters",
    "Art of ancient Egypt",
    "James Whistler's nocturnes",
    "Suprematism",
    "Diego Velázquez's court portraits",
    "Art of the Harlem Renaissance",
    "Tamara de Lempicka's Art Deco portraits",
    "Pointillism",
    "Mayan frescoes",
    "Artemisia Gentileschi's dramatic scenes",
    "Trompe-l'œil",
    "Henri Cartier-Bresson's candid photography",
    "Greek classical sculptures",
    "Jean-Michel Basquiat's graffiti art",
    "Chinese ink wash painting",
    "Paul Gauguin's Tahitian works",
    "Tribal art of the Maasai",
    "Yoko Ono's conceptual pieces",
    "Persian miniature painting",
    "Edward Hopper's scenes of solitude",
    "African Ndebele patterns",
    "Bridget Riley's optical illusions",
    "Russian iconography",
    "Ai Weiwei's contemporary installations",
    "Aztec stone carvings",
    "Camille Claudel's sculptures",
    "Indian Madhubani art",
    "David Hockney's pool scenes",
    "Japanese Sumi-e",
    "Fernand Léger's Tubism",
    "Polynesian tapa cloth art",
    "Lucian Freud's intimate portraits",
    "Korean Celadon pottery",
    "Agnes Martin's minimalist grids",
    "Native American ledger art",
    "Francis Bacon's distorted figures",
    "Turkish Iznik tiles",
    "Anselm Kiefer's textured canvases",
    "Balinese shadow puppets",
    "Jenny Holzer's truisms",
    "Maori tattoo art (Ta Moko)",
    "Piet Mondrian's De Stijl compositions",
    "Aboriginal dot painting",
    "Louise Bourgeois's surreal sculptures",
    "Islamic geometric patterns",
    "René Magritte's surreal scenes",
    "Tibetan thangka paintings",
    "Barbara Kruger's bold statements",
    "Scandinavian wood carving",
    "Giorgio de Chirico's metaphysical towns",
    "Mexican muralism",
    "Nam June Paik's video art",
    "Roman frescoes",
    "Tracey Emin's confessional art",
    "Thai traditional mural paintings",
    "Norman Rockwell's Americana",
    "Celtic knotwork",
    "Yves Klein's blue monochromes",
    "South American quipus",
    "Robert Rauschenberg's combines",
    "Mongolian throat singing",
    "Rachel Whiteread's negative space sculptures",
    "Arabesque designs",
    "Zaha Hadid's futuristic architecture",
    "Samoan tatau (tattoo art)",
    "Cy Twombly's scribbled canvases",
    "Rajasthani miniature paintings",
    "Joseph Beuys's social sculptures",
    "Byzantine enamels",
    "Marina Abramović's performance art",
    "Nigerian Nsibidi symbols",
    "Frank Stella's geometric works",
    "Indonesian Batik",
    "Damien Hirst's formaldehyde sculptures",
    "Kazimir Malevich's Black Square",
    "South African Ndebele beadwork",
    "Gerhard Richter's squeegee paintings",
    "Peruvian Nazca lines",
    "Banksy's street art",
    "Moroccan Zellige tilework",
    "Jean Dubuffet's Art Brut",
    "Navajo sand paintings",
    "Antoni Gaudí's modernist architecture",
    "Lygia Clark's interactive pieces",
    "Sicilian marionettes",
    "Mark Rothko's color fields",
    "Bhutanese thongdrel",
    "Christo and Jeanne-Claude's wrapped installations",
    "Inuit stone carvings",
    "Willem de Kooning's abstract expressionism",
    "Japanese Raku pottery",
    "Sophie Calle's narrative photography",
    "Ancient Greek vase painting",
    "Cindy Sherman's self-portraits",
    "Ottoman miniature paintings",
    "Edward Weston's photographic still lifes",
    "Sardinian Nuragic sculptures",
    "Vija Celmins's detailed surfaces",
    "Kente cloth from Ghana",
    "John Singer Sargent's portraiture",
    "Burmese puppetry",
    "Agnes Denes's environmental art",
    "Medieval illuminated manuscripts",
    "Chuck Close's pixelated portraits",
    "Korean Hanbok designs",
    "James Turrell's light installations",
    "Pacific Northwest Totem poles",
    "Dorothea Lange's documentary photography",
    "Russian lacquer art",
    "Jeff Koons's balloon animals",
    "Toda embroidery from India",
    "Richard Diebenkorn's Ocean Park series",
    "Samoan 'Siapo' (bark cloth art)",
    "Eva Hesse's post-minimalist sculptures",
    "Hungarian Herend porcelain",
    "Jackson Pollock's action painting",
    "Tibetan sand mandalas",
    "Faith Ringgold's story quilts",
    "Swedish Dala horse carvings",
    "Kara Walker's silhouette installations",
    "Bhutanese dzong architecture",
    "Ellsworth Kelly's hard-edge painting",
    "Philippine jeepney art",
    "Anish Kapoor's reflective sculptures",
    "Uzbek Suzani textiles",
    "Wayne Thiebaud's dessert paintings",
    "Balinese Kamasan style",
    "Sol LeWitt's conceptual art",
    "Colombian Molas",
    "Yayoi Kusama's polka dots",
    "Swiss paper cutting (Scherenschnitte)",
    "Robert Smithson's earthworks",
    "Tongan Tapa cloth",
    "Shirin Neshat's video installations",
    "Maasai beadwork",
    "Henri Cartier-Bresson's decisive moment",
    "Slovenian Idrija lace",
    "Dan Flavin's neon art",
    "Nigerian Aso Oke fabric",
    "Alberto Giacometti's elongated sculptures",
    "Sri Lankan cave paintings",
    "Bill Viola's video art",
    "Finnish Kalevala motifs",
    "Hilma af Klint's spiritual abstracts",
    "Chilean arpilleras",
    "Brice Marden's monochromatic panels",
    "Māori whakairo (wood carving)",
    "Betye Saar's assemblage art",
    "Icelandic turf houses",
    "Franz Kline's black and white paintings",
    "Kenyan kanga designs",
    "Louise Nevelson's monochromatic wood sculptures",
    "Bosnian stećci tombstones",
    "Sigmar Polke's layered paintings",
    "Vietnamese water puppetry",
    "Joan Mitchell's abstract landscapes",
    "Roman mosaics",
    "Joseph Cornell's shadow boxes",
    "Ecuadorian Tigua paintings",
    "Robert Irwin's perceptual art",
    "Algerian Tlemcen embroidery",
    "Peter Doig's dreamlike landscapes",
    "Mongolian Tsam masks",
    "Jasper Johns's flag paintings",
    "Peruvian retablos",
    "Agostino Carracci's engravings",
    "Bolivian carnival masks",
    "Frank Auerbach's thickly painted portraits",
    "Japanese Ukiyo-e prints",
    "Lee Krasner's collage paintings",
    "Moroccan Berber rugs",
    "David Hammons's body prints",
    "Sardinian murals (Murales)",
    "Howard Hodgkin's abstracted memories",
    "Cambodian shadow theatre",
    "Lyubov Popova's Constructivist works",
    "Pakistani truck art",
    "Sam Gilliam's draped canvases",
    "Romanian Easter eggs (ouă vopsite)",
    "Gordon Matta-Clark's architectural cuts",
    "Kyrgyz shyrdaks (felt rugs)",
    "R. B. Kitaj's narrative paintings"
]





