techniques = [
    "watercolor techniques", 
    "paper cut animation methods", 
    "spray painted realism", 
    "digital art rendering", 
    "oil painting strokes",
    "charcoal sketching",
    "digital 3D modeling",
    "encaustic painting",
    "bronze casting",
    "pointillist techniques",
    "collagraphy printmaking",
    "ceramic hand-building",
    "batik dyeing",
    "fresco painting",
    "macramé knotting",
    "lithography",
    "plein air painting",
    "cyanotype photography",
    "mosaic assembling",
    "drypoint etching",
    "origami folding",
    "marquetry",
    "intaglio printmaking",
    "acrylic pouring",
    "pyrography (wood burning)",
    "sgraffito on ceramics",
    "papercut silhouettes",
    "tape art",
    "gouache layering",
    "linocut carving",
    "wire sculpting",
    "pastel blending",
    "stained glass crafting",
    "collage assembling",
    "embroidery stitching",
    "terra cotta sculpting",
    "scratchboard art",
    "metal embossing",
    "quilling (paper coiling)",
    "sumi-e brush painting",
    "trompe-l'œil techniques",
    "glass blowing",
    "marbling on paper",
    "block printing on fabric",
    "egg tempera painting",
    "digital pixel art",
    "pencil hatching and cross-hatching",
    "airbrushing",
    "photomontage creation",
    "ink wash painting",
    "papier-mâché sculpting",
    "silverpoint drawing",
    "chiaroscuro shading",
    "digital vector art",
    "gold leaf gilding",
    "relief carving",
    "aquatint etching",
    "stop-motion animation",
    "mezzotint printmaking",
    "découpage layering",
    "sand animation",
    "tenebrism lighting",
    "faux finishing",
    "rotoscoping animation",
    "monotyping",
    "bead weaving",
    "grisaille painting",
    "lost-wax casting",
    "kirigami cutting",
    "digital matte painting",
    "frottage rubbing",
    "spray paint stenciling",
    "reverse glass painting",
    "woodblock printing (Moku Hanga)",
    "copperplate etching",
    "granulation in metalwork",
    "digital glitch art",
    "scrimshaw engraving",
    "opalotype photography",
    "textile felting",
    "pen and ink stippling",
    "cire perdue casting",
    "digital parallax animation",
    "spatter painting",
    "salt printing in photography",
    "chain stitch embroidery",
    "raku pottery firing",
    "digital VR sculpting",
    "brocade weaving",
    "wet-on-wet watercolor technique",
    "pâte de verre glasswork",
    "cross-stitching",
    "photogravure",
    "digital double exposure",
    "silk screen printing",
    "opalotype photography",
    "leather tooling",
    "risograph printing",
    "enamel cloisonné",
    "gum bichromate photography",
    "digital 3D printing",
    "soldering in metalwork",
    "VR painting in Tilt Brush",
    "wax resist dyeing",
    "augmented reality art",
    "tufting in textile design",
    "holographic displays",
    "underpainting in oils",
    "laser cutting and engraving",
    "platinum print photography",
    "motion capture animation",
    "sashiko stitching",
    "anamorphic art",
    "daguerreotype photography",
    "3D projection mapping",
    "kintsugi (golden joinery)",
    "digital morphing animation",
    "tapa cloth beating",
    "interactive digital installations",
    "tessellation patterns",
    "UV reactive painting",
    "millefiori in glasswork",
    "algorithmic art generation",
    "pinhole camera photography",
    "neural network art",
    "pysanky egg decorating",
    "lenticular printing",
    "copper repoussé and chasing",
    "digital ASCII art",
    "tatting lacework",
    "photorealistic painting",
    "interactive sound art",
    "cyanotype sun printing",
    "digital voxel art",
    "pulled sugar art",
    "360-degree video art",
    "knapping in stone work",
    "digital ray tracing",
    "bobbin lace making",
    "generative adversarial network (GAN) art",
    "parchment craft",
    "digital fractal rendering",
    "papercraft and origamic architecture",
    "thermal imaging art",
    "macrophotography",
    "digital particle simulations",
    "ferrofluid art",
    "digital depth mapping",
    "wet plate collodion process",
    "ARKit and ARCore augmented reality",
    "cuneiform tablet inscribing",
    "light painting photography",
    "trompe-l'œil mural painting",
    "digital fluid simulations",
    "fused glass art",
    "procedural generation in 3D modeling",
    "tapestry weaving",
    "haptic feedback art",
    "plaster casting",
    "digital photogrammetry",
    "fresco secco painting",
    "3D pen sculpting",
    "digital displacement mapping",
    "peyote beadwork",
    "time-lapse photography",
    "AI style transfer techniques",
    "hardstone carving",
    "digital procedural textures",
    "wire wrapping in jewelry",
    "stereoscopic 3D art",
    "thangka scroll painting",
    "digital MIDI art",
    "punched tin lanterns",
    "deepfake video generation",
    "batik crackle technique",
    "digital voxel sculpting",
    "papier collé (pasted paper art)",
    "real-time ray tracing",
    "murrine in glasswork",
    "digital neural style transfer",
    "tempera on panel painting",
    "interactive LED art",
    "intarsia wood inlay",
    "digital generative adversarial networks (GANs)",
    "marionette puppetry",
    "photocollage",
    "digital pixel sorting",
    "sand casting",
    "audio-reactive visual art",
    "mosaic tesserae setting",
    "digital kaleidoscopic art",
    "cut paper silhouette portraits",
    "3D LUTs in digital art",
    "digital metaball modeling",
    "scroll saw art",
    "daguerreotype photography",
    "digital procedural generation",
    "felted wool sculptures",
    "interactive projection mapping",
    "point lace techniques",
    "digital glitch effects",
    "lost foam casting",
    "AI-driven animation",
    "wood marquetry",
    "digital inverse kinematics",
    "stencil graffiti",
    "virtual reality sculpting",
    "chainmail weaving",
    "digital morph target animation",
    "eggshell mosaic",
    "real-time digital puppetry",
    "torn paper collage",
    "digital subsurface scattering",
    "opal art techniques",
    "digital inverse square lighting",
    "wire crochet jewelry",
    "algorithmic pattern generation",
    "suminagashi ink marbling",
    "digital ambient occlusion",
    "pressed flower art",
    "digital retopology in 3D modeling",
    "stained glass appliqué",
    "digital particle effects",
    "torchon lace techniques",
    "digital bump mapping",
    "pysanka egg dyeing",
    "digital skeletal animation",
    "tapa cloth art",
    "digital parallax scrolling",
    "metal chasing techniques",
    "digital procedural clouds",
    "washi paper crafting",
    "digital ray marching",
    "reverse appliqué techniques",
    "digital caustics simulation",
    "leather pyrography",
    "digital volumetric lighting",
    "copper tooling techniques",
    "digital fluid dynamics",
    "kumihimo braiding",
    "digital hair and fur simulation"
]








