
# Themes/Concepts
themes_concepts = [
    "grim dark cryptidwave", 
    "surrealism", 
    "romantic nostalgia", 
    "futuristic dystopia", 
    "Victorian elegance","post-apocalyptic wasteland",
    "Renaissance revival",
    "cosmic wonders",
    "urban decay",
    "mythical realms",
    "technological singularity",
    "deep-sea mysteries",
    "ancient civilizations",
    "whimsical fairy tales",
    "steampunk adventures",
    "interstellar exploration",
    "dreamlike surrealism",
    "wild west frontier",
    "cyberpunk dystopia",
    "enchanted forests",
    "neo-noir mysteries",
    "timeless romance",
    "gothic horror",
    "futuristic utopia",
    "prehistoric epochs",
    "magical academies",
    "vintage nostalgia",
    "alien landscapes",
    "medieval kingdoms",
    "tropical paradises",
    "arctic expeditions",
    "Victorian steampunk",
    "roaring twenties",
    "desert oases",
    "cosmic horror",
    "urban jungles",
    "underground caverns",
    "lost islands",
    "ancient Greek epics",
    "modern-day metropolis",
    "haunting ghost stories",
    "Afrofuturism",
    "post-war era",
    "prehistoric jungles",
    "psychedelic trips",
    "colonial era",
    "fantasy realms",
    "space-age retrofuturism",
    "ancient Egyptian myths",
    "post-modernism",
    "romanticism",
    "baroque grandeur",
    "industrial revolution",
    "golden age of piracy",
    "neoclassicism",
    "oriental tales",
    "wildlife safari",
    "Bauhaus minimalism",
    "Art Nouveau elegance",
    "carnival festivities",
    "underworld mythos",
    "celestial constellations",
    "Nordic legends",
    "Silk Road journeys",
    "Art Deco opulence",
    "mystical alchemy",
    "samurai code of honor",
    "hidden treasure quests",
    "jazz age soirées",
    "ancient druid rituals",
    "space colonization",
    "nomadic desert tribes",
    "Atlantean legends",
    "warrior code of chivalry",
    "bohemian rhapsodies",
    "voodoo and witchcraft",
    "underwater kingdoms",
    "cubist dimensions",
    "safari expeditions",
    "ancient Roman glories",
    "Himalayan monasteries",
    "impressionist daydreams",
    "aristocratic masquerades",
    "Native American folklore",
    "Olympian pantheon",
    "renaissance fairs",
    "Byzantine splendors",
    "urban street cultures",
    "tropical archipelagos",
    "Arabian nights",
    "Mayan prophecies",
    "avant-garde exhibitions",
    "meditative zen gardens",
    "Aztec empires",
    "boho-chic festivals",
    "Russian tsar dynasties",
    "Australian outback adventures",
    "Scottish highland tales",
    "abstract expressionism",
    "Caribbean pirate lore",
    "Bollywood drama",
    "Mesoamerican civilizations",
    "French Riviera escapades",
    "Saharan mirages",
    "Venetian masquerades",
    "African savannahs",
    "Pacific islander myths",
    "Andean highland cultures",
    "Gothic cathedrals",
    "Amazonian rainforests",
    "Tudor court intrigues",
    "Pacific Northwest legends",
    "Mongolian steppe tales",
    "Great Depression narratives",
    "Middle Eastern bazaars",
    "Antarctic expeditions",
    "Belle Époque Paris",
    "prehistoric cave paintings",
    "Southeast Asian temples",
    "American Civil War dramas",
    "Polynesian voyages",
    "Balkan folklore",
    "Victorian London mysteries",
    "Siberian wilderness",
    "Maori traditions",
    "Spanish flamenco passion",
    "Swiss alpine tales",
    "Japanese Edo period",
    "Aegean island myths",
    "Brazilian carnival vibes",
    "Canadian Rockies adventures",
    "Rajasthan palaces",
    "Berlin Wall histories",
    "Argentinian tango nights",
    "Viking sagas",
    "Mexican Day of the Dead",
    "Sicilian mafia stories",
    "Great Wall of China legends",
    "Egyptian pharaoh dynasties",
    "Irish fairy tales",
    "Korean Joseon dynasty",
    "Appalachian folktales",
    "Moroccan desert caravans",
    "Greek tragedies",
    "Alaskan frontier tales",
    "Nigerian Yoruba myths",
    "Icelandic sagas",
    "Peruvian Inca legends",
    "Balinese dance rituals",
    "Wild West gunslingers",
    "Scandinavian fjord tales",
    "Zulu warrior epics",
    "Mediterranean island stories",
    "Trans-Siberian railway journeys",
    "Celtic druid legends",
    "Amazonian tribal cultures",
    "New York jazz age",
    "Hawaiian luaus",
    "Russian ballet narratives",
    "Chilean Andes mysteries",
    "Portuguese fado melancholy",
    "Malian desert blues",
    "Cambodian Angkor tales",
    "Ukrainian Cossack legends",
    "Australian Aboriginal Dreamtime",
    "Bhutanese Himalayan sanctuaries",
    "Cuban salsa rhythms",
    "Mongolian throat singing traditions",
    "Finnish Lapland sagas",
    "Colombian coffee region tales",
    "Ethiopian highland epics",
    "Vietnamese lantern festivals",
    "Bavarian fairy tales",
    "Israeli kibbutz stories",
    "Bolivian salt flat wonders",
    "Nepalese Sherpa legends",
    "Hungarian Magyar folklore",
    "Tibetan monk rituals",
    "Uruguayan gaucho tales",
    "Belgian medieval towns",
    "Kenyan Maasai traditions",
    "Norwegian Viking ships",
    "Bangladeshi river tales",
    "Roman gladiator epics",
    "Costa Rican rainforest adventures",
    "Bulgarian rose valleys",
    "Jordanian Petra mysteries",
    "Estonian forest legends",
    "Sri Lankan tea plantations",
    "Panamanian canal stories",
    "Belarusian ancient castles",
    "Latvian midsummer tales",
    "Lithuanian amber coasts",
    "Kazakhstani steppe nomads",
    "Macedonian ancient ruins",
    "Slovakian mountain tales",
    "Slovenian alpine stories",
    "Cypriot Mediterranean legends",
    "Luxembourgish fairy tales",
    "Maltese knight epics",
    "Icelandic geothermal wonders",
    "Taiwanese lantern festivals",
    "Filipino island legends",
    "Indonesian shadow puppetry",
    "Pakistani mountain tales",
    "Afghan Silk Road stories",
    "Armenian monastery legends",
    "Maldivian island paradises",
    "Georgian wine valleys",
    "Azerbaijani fire temples",
    "Uzbek Silk Road cities",
    "Kyrgyz nomadic traditions",
    "Turkmen desert landscapes",
    "Tajik mountain tales",
    "Laotian Mekong stories",
    "Myanmar pagoda legends",
    "Bruneian water village tales",
    "Fijian kava ceremonies",
    "Tongan island myths",
    "Samoan warrior dances",
    "Vanuatuan volcano rituals",
    "Solomon Islander ancestral tales",
    "Micronesian navigational legends",
    "Palauan underwater wonders",
    "Marshallese atoll stories",
    "Nauruan phosphate tales",
    "Tuvaluan rising sea legends",
    "Kiribati equator myths",
    "Moldovan cave monasteries",
    "Montenegrin coastal tales",
    "Albanian eagle legends",
    "Kosovan medieval heritage",
    "Bosnian bridge stories",
    "Croatian Adriatic wonders",
    "Serbian folklore dances",
    "Romanian Transylvanian tales",
    "Polish medieval castles",
    "Czech Bohemian legends",
    "Slovak Tatra mountain tales",
    "Hungarian thermal baths",
    "Austrian alpine stories",
    "Swiss watchmaking tales",
    "Dutch tulip fields",
    "Belgian chocolate legends",
    "Luxembourg fortress tales",
    "Monacan casino stories",
    "Liechtensteiner alpine myths",
    "Andorran Pyrenees legends",
    "San Marinese medieval tales",
    "Vatican religious wonders",
    "Malagasy lemur forests",
    "Seychellois coral atolls",
    "Mauritian island tales",
    "Comorian volcanic landscapes",
    

]














